[package]
name = "deposit_pool"
edition = "2024.beta" 
authors = ["Talus Labs <hi@taluslabs.com>"]

[dependencies]
Talus = {local = "../talus"}
loyalty = {local = "../loyalty"}

[addresses]
deposit_pool = "0x0"
